//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_422_Nigmatov.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Match()
        {
            this.MatchMember1 = new HashSet<MatchMember>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Tournament_Id { get; set; }
        public Nullable<System.DateTime> DateTimeStart { get; set; }
        public Nullable<int> Winner_Id { get; set; }
        public Nullable<System.TimeSpan> Duration { get; set; }
    
        public virtual MatchMember MatchMember { get; set; }
        public virtual Tournament Tournament { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatchMember> MatchMember1 { get; set; }
    }
}
