//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_422_Nigmatov.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Tournament_Entities : DbContext
    {
        public Tournament_Entities()
            : base("name=Tournament_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Game> Game { get; set; }
        public virtual DbSet<Match> Match { get; set; }
        public virtual DbSet<MatchMember> MatchMember { get; set; }
        public virtual DbSet<Organizator> Organizator { get; set; }
        public virtual DbSet<Player> Player { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Team> Team { get; set; }
        public virtual DbSet<TeamRole> TeamRole { get; set; }
        public virtual DbSet<TournamentFormat> TournamentFormat { get; set; }
        public virtual DbSet<TournamentMemberStatus> TournamentMemberStatus { get; set; }
        public virtual DbSet<TournamentMemeber> TournamentMemeber { get; set; }
        public virtual DbSet<TournamentOrganizator> TournamentOrganizator { get; set; }
        public virtual DbSet<TurnirStatus> TurnirStatus { get; set; }
        public virtual DbSet<Tournament> Tournament { get; set; }
    }
}
