//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_422_Nigmatov.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Nickname { get; set; }
        public string Contacts { get; set; }
        public Nullable<int> TeamRole_Id { get; set; }
        public Nullable<int> Team_Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual TeamRole TeamRole { get; set; }
    }
}
