//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_422_Nigmatov.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TournamentMemeber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TournamentMemeber()
        {
            this.MatchMember = new HashSet<MatchMember>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Team_Id { get; set; }
        public Nullable<int> Tournament_Id { get; set; }
        public Nullable<int> TournamentMemberStausId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatchMember> MatchMember { get; set; }
        public virtual Team Team { get; set; }
        public virtual Tournament Tournament { get; set; }
        public virtual TournamentMemberStatus TournamentMemberStatus { get; set; }
    }
}
