//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_422_Nigmatov.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tournament
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tournament()
        {
            this.Match = new HashSet<Match>();
            this.TournamentMemeber = new HashSet<TournamentMemeber>();
            this.TournamentOrganizator = new HashSet<TournamentOrganizator>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Game_Id { get; set; }
        public Nullable<int> TournamentFormat_Id { get; set; }
        public Nullable<System.DateTime> DateOfEvent { get; set; }
        public Nullable<int> PrizeFund { get; set; }
        public Nullable<int> TournamentStatus_Id { get; set; }
        public Nullable<int> MembersAmount { get; set; }
        public string AddionalLimits { get; set; }
    
        public virtual Game Game { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Match> Match { get; set; }
        public virtual TournamentFormat TournamentFormat { get; set; }
        public virtual TurnirStatus TurnirStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TournamentMemeber> TournamentMemeber { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TournamentOrganizator> TournamentOrganizator { get; set; }
    }
}
