//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_422_Nigmatov.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TournamentOrganizator
    {
        public int Id { get; set; }
        public Nullable<int> Tournament_Id { get; set; }
        public Nullable<int> Organizator_Id { get; set; }
    
        public virtual Organizator Organizator { get; set; }
        public virtual Tournament Tournament { get; set; }
    }
}
